env:
  action_frequency: 60                  # (int): environment executes action at the action_frequency rate
  physics_frequency: 60                 # (int): physics frequency (1 / physics_timestep for physx)
  device: null                          # (None or str): specifies the device to be used if running on the gpu with torch backend
  automatic_reset: false                # (bool): whether to automatic reset after an episode finishes
  flatten_action_space: false           # (bool): whether to flatten the action space as a sinle 1D-array
  flatten_obs_space: false              # (bool): whether the observation space should be flattened when generated
  use_external_obs: false               # (bool): Whether to use external observations or not
  initial_pos_z_offset: 0.1
  external_sensors:                     # (None or list): If specified, list of sensor configurations for external sensors to add. Should specify sensor "type" and any additional kwargs to instantiate the sensor. Each entry should be the kwargs passed to @create_sensor, in addition to position, orientation
    - sensor_type: VisionSensor
      modalities: [rgb, depth, bbox_2d_tight, depth_linear]
      sensor_kwargs:
        image_height: 128
        image_width: 128
      local_position: [0, 0, 1.0]
      local_orientation: [0.707, 0.0, 0.0, 0.707]

depth:
  viewer_width: 720
  viewer_height: 720
# robots:
#   camera_width: 1280
#   camera_width: 720
scene:
  type: InteractiveTraversableScene
  trav_map_resolution: 0.25
  default_erosion_radius: 0.0
  trav_map_erosion: 2
  trav_map_with_objects: true
  build_graph: true
  num_waypoints: 1
  waypoint_resolution: 0.25
  load_object_categories: null
  not_load_object_categories: null
  load_room_types: null
  load_room_instances: null
  seg_map_resolution: 0.1
  scene_source: OG
  step_size: 0.25
  turn_size: 1.570796326794896619
  build_from_source: false
  include_robots: true

# robots:
#   - type: Fetch
#     obs_modalities: [scan, rgb, depth, bbox_2d_tight]
#     # obs_modalities: [scan, rgb, depth,camera,bbox_2d_tight]
#     scale: 1.0
#     step_size: 0.25
#     turn_size: 1.570796326794896619
#     camera_height: 256 
#     camera_width: 256
#     camera_focal_length: 6
#     self_collision: false
#     action_normalize: true
#     action_type: continuous
#     grasping_mode: physical
#     # grasping_mode: magic
#     rigid_trunk: false
#     default_trunk_offset: 0.365
#     default_arm_pose: diagonal30
#     default_reset_mode: tuck
#     # reset_joint_pos: tuck
#     sensor_config:
#       VisionSensor:
#         sensor_kwargs:
#           image_height: 256
#           image_width: 256
#       ScanSensor:
#           sensor_kwargs:
#             min_range: 0.05
#             max_range: 10.0
#     controller_config:
#       base:
#         name: DifferentialDriveController
#       arm_0:
#         name: InverseKinematicsController
#         # kv: 2.0
#       gripper_0:
#         name: MultiFingerGripperController
#         mode: binary
#       camera:
#         name: JointController
#         use_delta_commands: False
